### ISSUE TITLE
RFC for Normal, Backup and Sacrificial copies having different hash-order name

### ISSUE THREAD

**Issue by maqi** [maidsafe/safe_vault#292]
Currently, DataManger treated them as the same name of a chunk.
However their name shall be in different hash order.

The options that the current rule of choosing DM and then PN shall be changed to : 
1,
DM(normal) = hash(im.content) ,  2 copies on the two closest node to the DM(normal)
DM(backup) = hash(hash(im.content)) ,  2 copies on the two closest node to the DM(backup)
DM(sacrificial) = hash(hash(hash(im.content))) ,  2 copies on the two closest node to the DM(sacrificial)

2, 
DM(normal) = hash(im.content) ,  
2 copies on the two closest node to the hash(im.content)
2 copies on the two closest node to the hash(hash(im.content)) 
2 copies on the two closest node to the  hash(hash(hash(im.content)))

There are also existing put/get flow and error_handling flow need to be reviewed after such change implemented.

**Comment by Fraser999** [comment]
I don't think we should use the hash of the hash paradigm, since this could yield the same group for the normal, backup and sacrificial copies (the probability of this increasing to 1 as the network size decreases).

I think we should XOR the chunk ID to yield each group.  While this should be more efficient than repeated hashing, more importantly it should yield groups which don't intersect (except for tiny networks).

Essentially the "normal" group will be XOR with `000...000` i.e. equivalent to the ID.  The sacrificial group will be XOR with `fff...fff`, i.e. the furthest location in the address space; and the backup will be in the middle; i.e. XOR with `800...000`.

I also don't think we should reduce the copies to 2.  I'd prefer to address the Routing issue which makes using 4 copies problematic.

**Comment by maqi** [comment]
The required RFC is now starts proposing in https://github.com/maidsafe/rfcs/pull/59 .
As this issue was created just for "note down" purpose, and the RFC work has started,
so currently closing this issue.
Any further comment or actions shall be based on the RFC PR https://github.com/maidsafe/rfcs/pull/59
