### ISSUE TITLE
no chunks stored in the Temp/safe-vault folder

### ISSUE THREAD

**Issue by citan** [maidsafe/safe_vault#504]
Testnet 4, vault v0.9.0
Windows 10-64

--

Despite having launched the vault several hours ago, the folder created in AppData\Local\Temp folder to store chunks has received no chunks.
The vault is connected to 30 other peers, and regularly logs info (cf attachment).
[terminal_output_extract.txt](https://github.com/maidsafe/safe_vault/files/326867/terminal_output_extract.txt)

Among this, some strange lines appear (the end is particularly bugging):

INFO 10:13:15.569371400 [safe_vault::personas::data_manager data_manager.rs:308] Stats : Client Get requests received 5 ; Data stored - **_ID 0 - SD 0 - total 0 bytes_**

It could be related to the firewall my employer is using: when connecting on its network, the issue occurs everytime, while it does not occur if I connect to my phone's hotspot. I do not know what they could be using to block the traffic though...

**Comment by afck** [comment]
Thank you for reporting this!
Are there any log entries like `Cache Stats - Expecting 2 Get responses. 3 entries in data_holders.`? (I didn't find any in the log extract.) If your vault was ever expecting chunks but didn't get them, it might be due to insufficient bandwidth.
Do you see any entries like `Indirect connections: 2, tunneling for: 0`?

**Comment by citan** [comment]
Unfortunately the entries you mentionned are not present in Node.log. I am enclosing it in the hope that you can find useful info. 
Fyi, the entries reported in my message above can be found at line 9,654.
I hope that this will be usefull, 
[Node.zip](https://github.com/maidsafe/safe_vault/files/328942/Node.zip)

Best regards,

**Comment by afck** [comment]
Since everything else seems fine (routing table size etc.) and it didn't even expect any Get responses, I'd almost guess your vault might just have been unlucky (or lucky, if it's lazy :-D): It didn't _have_ to store any data!
In a large network with lots of data, since chunk names and node names are randomly distributed, this will even out, but in a small test network like this one, the storage load can vary a lot between individual vaults. If a node ends up in a place densely populated by other nodes but with very little data, it might end up not being responsible for any chunks.

So I'll close this issue for now. But if you observe any pattern (e. g. the vault you start first always has much more data than the second one), please reopen it.
