### ISSUE TITLE
ok i'm not sure if this is the correct place for the issue ... it's about a datastructure inside test12

### ISSUE THREAD

**Issue by rid-dim** [maidsafe/safe_vault#602]
i was posting excessively and stressing the chat-app with some error-messages something strange happened:

![bildschirmfoto vom 2017-02-04 21-14-28](https://cloud.githubusercontent.com/assets/23142572/22621337/9107200c-eb21-11e6-890d-2586181446fe.png)
![bildschirmfoto vom 2017-02-04 21-16-47](https://cloud.githubusercontent.com/assets/23142572/22621339/96229184-eb21-11e6-8c3f-07f7970c4909.png)

you can see at 20:10:02 the letter is flipping from f to g and back ... to me it seems there are 2 concurrent versions of the file now in test12

is that possible ...? is that only possible in very small networks ..?
to me it looks more like a vault-bug than a bug in the chat-app ...?

**Comment by afck** [comment]
I don't think so: If there were two versions, the client wouldn't get a response at all for that data anymore. (Also, it shouldn't happen in the first place, of course.)
To debug this further, we would need to know exactly when the chat app requests that data.

**Comment by rid-dim** [comment]
sorry sorry sorry - i completely forgot about this >.<

uhm
this peace of data was requested at the time i wrote my report - uhm - and as the timetags indicate
it was created 04th Feb 20:10:02 GMT (it was requested after that several times per second by the chat for at least 15 minutes ... probably more like an hour or so ^^)

**Comment by afck** [comment]
Ah, sorry, I meant we'd need to know under which circumstances the chat app creates what kind of data. At a glance it looks to me like it stores its message handles in an appendable data and the message in an immutable data chunk. The latter doesn't have different versions at all, and the former will be replaced very soon by "mutable data": [RFC 47](https://github.com/maidsafe/rfcs/blob/master/text/0047-mutable-data/0047-mutable-data.md)

In general it's hard to draw conclusions about the backend (the network/vaults) based on the behaviour of a particular app. In most cases it is best to file an [issue with the app itself](https://github.com/hunterlester/safe-chat/issues) first, as the app's authors will be in a better position to judge whether it is indeed an issue with data handling in vaults.

I'll close this for now, since appendable data is obsolete anyway.
